#!/bin/bash

# rsync -azv --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/Al_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/Al_research/
# rsync -azv --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/allxfs1_outputs/allxfs1_Al* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/allxfs1/Al_research/
# rsync -azv -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/*Electron_dyn_k_vals.npy  ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/10_77eV_1_75_rs/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/10_77eV_1_75_rs/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/10_77eV_1_75_rs/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/10_77eV_1_75_rs/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/21_54eV_1_75_rs/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/21_54eV_1_75_rs/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_9c_gamma/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9c_gamma/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_9c_gamma/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9c_gamma/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_9c_gamma/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9c_gamma/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_9c_gamma/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9c_gamma/

# scp -r -oProxyCommand="ssh -W %h:%p campbellt@bastion.physics.ox.ac.uk" campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/backup/BohmSPH_overview_paper_data/scarf_H_21_54eV_1_75_rs_min_9c/ele_ID_data_check11.npy ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9c/
# scp -r -oProxyCommand="ssh -W %h:%p campbellt@bastion.physics.ox.ac.uk" campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/backup/BohmSPH_overview_paper_data/scarf_H_21_54eV_1_75_rs_min_9c/ele_h_data_check11.npy ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9c/
# scp -r -oProxyCommand="ssh -W %h:%p campbellt@bastion.physics.ox.ac.uk" campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/backup/BohmSPH_overview_paper_data/scarf_H_21_54eV_1_75_rs_min_9c/ele_x_data_check11.npy ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9c/

# scp -r -oProxyCommand="ssh -W %h:%p campbellt@bastion.physics.ox.ac.uk" campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scale_temp_long/scarf_H_21_54eV_1_75_rs_min_scale_temp_1a_long/ele_h_target.npy ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scale_temp_long/scarf_H_21_54eV_1_75_rs_min_scale_temp_1a_long/
# scp -r -oProxyCommand="ssh -W %h:%p campbellt@bastion.physics.ox.ac.uk" campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scale_temp_long/scarf_H_21_54eV_1_75_rs_min_scale_temp_1a_long/ele_x_target.npy ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scale_temp_long/scarf_H_21_54eV_1_75_rs_min_scale_temp_1a_long/

# scp -r -oProxyCommand="ssh -W %h:%p campbellt@bastion.physics.ox.ac.uk" campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_simple_32c/ele_xyzh_data_check11.dump ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_simple_32c/


rsync -azv --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_QHO_stability_test* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/conservation_testing/
rsync -azv --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_coul_stability_test* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/conservation_testing/


# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_simple_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_simple_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/


# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_9d_gamma/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9d_gamma/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scarf_H_21_54eV_1_75_rs_min_9d_gamma/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scarf_H_21_54eV_1_75_rs_min_9d_gamma/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scale_temp_long/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scale_temp_long/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/scale_temp_long/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/21_54eV_1_75_rs/scale_temp_long/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/backup/scarf_H_10_77eV_1_75_rs_min_123nve/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/10_77eV_1_75_rs/scarf_H_10_77eV_1_75_rs_min_123nve/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/backup/scarf_H_10_77eV_1_75_rs_min_123nve/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/10_77eV_1_75_rs/scarf_H_10_77eV_1_75_rs_min_123nve/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/backup/scarf_H_10_77eV_1_75_rs_min_124nve/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/10_77eV_1_75_rs/scarf_H_10_77eV_1_75_rs_min_124nve/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/mnt/ext_drive/data/tcampbell/H_research/backup/scarf_H_10_77eV_1_75_rs_min_124nve/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/10_77eV_1_75_rs/scarf_H_10_77eV_1_75_rs_min_124nve/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/thermalisation/*constant_KE_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/constant_KE/
# rsync -azv --exclude='*.npy*' --exclude='*.dump' --exclude='*.rdf' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/thermalisation/*_constant_KE_*/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/constant_KE/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/thermalisation/*constant_temp_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/constant_temp/
# rsync -azv --exclude='*.npy*' --exclude='*.dump' --exclude='*.rdf' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/thermalisation/*_constant_temp_*/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/constant_temp/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/thermalisation/*coupling_scan_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/coupling_scan/


# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_z_4/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/ele_KE_Al_solid_z_4/
# rsync -azv --exclude='*.npy*' --exclude='*.dump' --exclude='*.rdf' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_z_4/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/ele_KE_Al_solid_z_4/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_jellium_z_4/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/ele_KE_Al_solid_jellium_z_4/
# rsync -azv --exclude='*.npy*' --exclude='*.dump' --exclude='*.rdf' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_jellium_z_4/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/ele_KE_Al_solid_jellium_z_4/


# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_Z_4_Nepe_8_Gamma_0_0683_dist_evol* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/
# rsync -azv --exclude='*.npy*' --exclude='*.dump' --exclude='*.rdf' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_Z_4_Nepe_8_Gamma_0_0683_dist_evol* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/


# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/
# rsync -azv --exclude='*.npy*' --exclude='*.dump' --exclude='*.rdf' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/

# rsync -azv -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_z_4/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/ele_KE_Al_solid_z_4/
# rsync -azv -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_z_5/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/ele_KE_Al_solid_z_5/
# rsync -azv -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_z_6/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/ele_KE_Al_solid_z_6/
# rsync -azv -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/ele_KE_Al_solid_jellium_z_4/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/ele_KE_Al_solid_jellium_z_4/


# rsync -azv --exclude='*vels*' --exclude='*.dump' --exclude='*.rdf' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/ele_therm_research/scarf_e_therm_Z_4_coup_batch1_5a/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/ele_therm_research/scarf_e_therm_Z_4_coup_batch1_5a/


# rsync -azv --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/H_ground/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/H_ground/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/H_ground/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/H_ground/


# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/Al_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/Al_research/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/Al_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/Al_research/


# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_coul_long_sub* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/coul_testing/
# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_confine_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/confine_testing/
# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_CoM_thermo_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/CoM_thermo_testing/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_CoM_thermo_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/CoM_thermo_testing/

# rsync -azv --exclude='*_vel_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_H_ground_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/H_ground_testing/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_H_ground_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/H_ground_testing/

# rsync -azv --exclude='*_vel_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_e_therm* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/ele_therm_testing/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_e_therm* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/ele_therm_testing/

# rsync -azv --exclude='*_vel_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_BohmPot_end_test* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/BohmPotTesting/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_BohmPot_end_test* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/BohmPotTesting/

# rsync -azv --exclude='*_vel_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_H_10_77eV_2_rs_min_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/BohmPotTesting/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_H_10_77eV_2_rs_min* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/BohmPotTesting/


# rsync -azv --exclude='*_vel_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_H_21_54eV_1_75_rs_min* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/trajectories_testing/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_H_21_54eV_1_75_rs_min* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/trajectories_testing/

# rsync -azv --exclude='ele_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_CoM_thermo_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/CoM_thermo_testing/
# rsync -azv --exclude='ele_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_MFBohm_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/MFBohm_testing/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/allxfs1_outputs/allxfs1_H* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/allxfs1/H_research/
# rsync -azv --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/Be_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/Be_research/

# --exclude='*_ISF.*'