#!/bin/bash

# rsync -azv --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/Al_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/Al_research/
# rsync -azv --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/allxfs1_outputs/allxfs1_Al* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/allxfs1/Al_research/
# rsync -azv -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/*Electron_dyn_k_vals.npy  ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/

rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/
rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/H_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/H_research/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/Al_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/Al_research/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/Al_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/Al_research/


# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_coul_long_sub* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/coul_testing/
# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_confine_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/confine_testing/
# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_CoM_thermo_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/CoM_thermo_testing/
# rsync -azv --exclude='ele_CoM*' --exclude='vel_*' --exclude='*_vel*' --exclude='*_Sk.*' --exclude='*_Sk_e_freq*' --exclude='*_unitk*' --exclude='*_k_e_freq*' --exclude='*_k.*' --exclude='*_ID*' --exclude='*_h*' --exclude='*_x*' --exclude='*_x_e_freq*' --exclude='*_corr.*' --exclude='*_corr_*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_nk_*' --exclude='*_F.*' --exclude='*_F_u*' --exclude='*_F_e*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_CoM_thermo_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/CoM_thermo_testing/

# rsync -azv --exclude='ele_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_CoM_thermo_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/CoM_thermo_testing/
# rsync -azv --exclude='ele_*' --exclude='vel_*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SPH_Bohm/hedp_SPH_MFBohm_test_* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/hedp64/MFBohm_testing/

# rsync -azv --exclude='*.npy*' --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/allxfs1_outputs/allxfs1_H* ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/allxfs1/H_research/
# rsync -azv --exclude='*_corr.*' --exclude='*_h.*' --exclude='*_x.*'  --exclude='*_nk.*' --exclude='*_F.*' --exclude='*_F_u.*' --exclude='log.*' --exclude='*.rdf' --exclude='*.dump' --exclude='*.cpp' --exclude='*.h' -e 'ssh -o "ProxyCommand ssh -A campbellt@bastion.physics.ox.ac.uk -W %h:%p"' campbell@allxdaq12.nat.physics.ox.ac.uk:/data/tcampbell/LAMMPS/SCARF_outputs/Be_research/ ~/Documents/GitHub/LAMMPS_SPH_Bohm/outputs/SCARF/Be_research/

# --exclude='*_ISF.*'